### ISSUE TITLE
Cancel ItemSwipe operation

### ISSUE THREAD

**Issue by maxstricker** [FrayxRulez/SwipeListView#14]
Hi,

how can I cancel the swipe inside SwipeListView_ItemSwipe and reset the view to look like initially.
Lets say a user swipes right, inside the SwipeListView_ItemSwipe I want to check if the operation is possible and return if some condition is not satisfied.
How can I reset the visual layout to the one before swiping?
I found SwipeListViewItem.ResetSwipe() which could be the method I need, but inside the SwipeListView_ItemSwipe I am unable to get the current SwipeListViewItem.
Any ideas?

**Comment by FrayxRulez** [comment]
You can use `ListView.ContainerFromItem` method to get the `SwipeListViewItem` from the `e.SwipedItem` property

**Comment by maxstricker** [comment]
Perfect, thanks.
Appreciate the fast response.
