### ISSUE TITLE
Selection Changed

### ISSUE THREAD

**Issue by aledut** [FrayxRulez/SwipeListView#2]
Hello, i am trying to use this code but the Selection Cnahed event does not fire.  Why this only works with item click?

If i set to isClickEnable to false and use SelectionChanged then the swipe stop working...

Is there a way to make it work?

Regards

**Comment by FrayxRulez** [comment]
Hi, actually swipe is intended to work only if SelectionMode == None.

**Comment by aledut** [comment]
Hi.

I know it is working like this.

But in Outlook mail, you have the swipe even with selecion enabled.  When
you use the portraid mode you can select the item to see the preview, the
item show its background as selected and still you have the swipe option.

2015-10-15 16:58 GMT-03:00 Fela Ameghino notifications@github.com:

**Comment by FrayxRulez** [comment]
Ok, source code updated. Now I'll update NuGet package too.

**Comment by aledut** [comment]
Wow that was fast!

Amazing, thanks a lot Fela!!!!!

2015-10-15 18:11 GMT-03:00 Fela Ameghino notifications@github.com:

**Comment by FrayxRulez** [comment]
Ok, update pushed on NuGet, check of updates on VS in a couple of minutes :)

**Comment by aledut** [comment]
Fela, actually now i am getting the same error when i tried using the nuget
package:

"Cannot find a Resource with the Name/Key ListViewItemMargin [Line: 25
Position: 35]"

When i used nugget o got this error, then i tried just copying the classes
from your project and i manage to get it working.

Now even with the classes only i am getting this error, what should i do?

Windows 10 Universal App

2015-10-15 18:28 GMT-03:00 Fela Ameghino notifications@github.com:

**Comment by aledut** [comment]
Ok i got it working, was using the wrong generic.xaml

thanks

2015-10-15 19:17 GMT-03:00 Alessandro Dutenhefner aledut@gmail.com:
